### PR TITLE
It is now possible to use _MyScriptX to dynamically call Set player weapon

### PR DESCRIPTION
**Pull request by EvidentlyCube**
[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=42307)

### CODE REVIEW

**Comment by mrimer** [comment]
Please rebase this PR following the merging of the briar fix PR

**Review by mrimer — CHANGES_REQUESTED** [review]
Rebase

**Comment by EvidentlyCube** [comment]
This targets 5.2 so it has to wait for 5.2 to be rebased on top of master

**Comment by mrimer** [comment]
Okay, I'll provide that soon.

**Pull request closed without merging**
