### PR TITLE
Remove Wait for Weapon script command

### PR DESCRIPTION
**Pull request by Hypexion**
A number of PRs (#6, #9 and #13) were merged to add a new script command, Wait for Weapon. If new script commands require a major version, this work will have to removed for now, and reapplied later.

This PR does the removing part by reverting the PRs that added Wait for Weapon and cleaning up places any other places that refer to it.

Please be aware that #20, which adds Set Behaviour is built assuming these PRs exist, so when they are readded, they must be merged before that work.

### CODE REVIEW

**Comment by mrimer** [comment]
Ah, gotcha!  I hadn't realized that previous merges hadn't been released yet, but this makes sense in hindsight. Thank you for being conscientious on this point.  Yes, let's back out these new features for now, and we'll reintroduce them together with Set Behaviour. 

How about I merge this change, and then would you please put up a fresh PR with these feature additions, which we can label to merge into 5.2?

Suggest we work through whichever bugs and non-version-breaking feature changes we'd like to make for 5.1.2, and once we have these released, we'll immediately provide a 5.2 alpha build for testers to begin playing with.

**Comment by mrimer** [comment]
@Hypexion , I'd like to capture other changes that have been made since 5.1.1 was released?

Would you please provide me either a list of commits, or the earliest commit, that you're aware of, which I should review and capture for the 5.1.2 patch?

**Comment by Hypexion** [comment]
> 
> 
> @Hypexion , I'd like to capture other changes that have been made since 5.1.1 was released?
> 
> Would you please provide me either a list of commits or PRs, or the earliest commit/PR, that you're aware of, which I should review and capture for the 5.1.2 patch?
> 
> Edit: Is it just all of the PRs that have been merged in the repo history?

All the changes that were merged are new fixes since the last official release. This should be the only new feature, with the rest being bug fixes.

**Comment by mrimer** [comment]
> All the changes that were merged are new fixes since the last official release. This should be the only new feature, with the rest being bug fixes.

Thank you.  I'll familiarize myself with these fixes.

**Pull request merged**
