### PR TITLE
Customise scoring

### PR DESCRIPTION
**Pull request by kieranmillar**

### CODE REVIEW

**Comment by kieranmillar** [comment]
Whoops

**Comment by kieranmillar** [comment]
There I fixed it. Accidentally pointed it at master, not rpg-1.3-dev.

This PR is best explained by this forum thread. Includes a screenshot of how it looks:
https://forum.caravelgames.com/viewtopic.php?TopicID=44777

**Review by mrimer — APPROVED** [review]
Thank you for the PR! Very careful and thorough changes.
I like this addition.

**Comment by mrimer** [comment]
In addition to patching the new MID texts in DbBase.cpp, we also need to add them to a Texts .uni file (probably the one where other script vars are) so they will be added to the .dat file on next .dat file rebuild.

**Pull request merged**
